// Code generated by entc, DO NOT EDIT.

package purpose

const (
	// Label holds the string label denoting the purpose type in the database.
	Label = "purpose"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPurpose holds the string denoting the purpose field in the database.
	FieldPurpose = "purpose"

	// EdgeRoomuses holds the string denoting the roomuses edge name in mutations.
	EdgeRoomuses = "roomuses"

	// Table holds the table name of the purpose in the database.
	Table = "purposes"
	// RoomusesTable is the table the holds the roomuses relation/edge.
	RoomusesTable = "roomuses"
	// RoomusesInverseTable is the table name for the Roomuse entity.
	// It exists in this package in order to avoid circular dependency with the "roomuse" package.
	RoomusesInverseTable = "roomuses"
	// RoomusesColumn is the table column denoting the roomuses relation/edge.
	RoomusesColumn = "purpose_id"
)

// Columns holds all SQL columns for purpose fields.
var Columns = []string{
	FieldID,
	FieldPurpose,
}

var (
	// PurposeValidator is a validator for the "purpose" field. It is called by the builders before save.
	PurposeValidator func(string) error
)
