// Code generated by entc, DO NOT EDIT.

package activities

const (
	// Label holds the string label denoting the activities type in the database.
	Label = "activities"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDetail holds the string denoting the detail field in the database.
	FieldDetail = "detail"
	// FieldStarttime holds the string denoting the starttime field in the database.
	FieldStarttime = "starttime"
	// FieldEndtime holds the string denoting the endtime field in the database.
	FieldEndtime = "endtime"

	// EdgeActivitytype holds the string denoting the activitytype edge name in mutations.
	EdgeActivitytype = "activitytype"
	// EdgeAcademicyear holds the string denoting the academicyear edge name in mutations.
	EdgeAcademicyear = "academicyear"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"

	// Table holds the table name of the activities in the database.
	Table = "activities"
	// ActivitytypeTable is the table the holds the activitytype relation/edge.
	ActivitytypeTable = "activities"
	// ActivitytypeInverseTable is the table name for the ActivityType entity.
	// It exists in this package in order to avoid circular dependency with the "activitytype" package.
	ActivitytypeInverseTable = "activity_types"
	// ActivitytypeColumn is the table column denoting the activitytype relation/edge.
	ActivitytypeColumn = "ActivityTypeID"
	// AcademicyearTable is the table the holds the academicyear relation/edge.
	AcademicyearTable = "activities"
	// AcademicyearInverseTable is the table name for the AcademicYear entity.
	// It exists in this package in order to avoid circular dependency with the "academicyear" package.
	AcademicyearInverseTable = "academic_years"
	// AcademicyearColumn is the table column denoting the academicyear relation/edge.
	AcademicyearColumn = "AcademicYearID"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "activities"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "UserID"
)

// Columns holds all SQL columns for activities fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDetail,
	FieldStarttime,
	FieldEndtime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Activities type.
var ForeignKeys = []string{
	"AcademicYearID",
	"ActivityTypeID",
	"UserID",
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DetailValidator is a validator for the "detail" field. It is called by the builders before save.
	DetailValidator func(string) error
)
