// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/OMENX/app/ent/activities"
	"github.com/OMENX/app/ent/activitytype"
	"github.com/OMENX/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ActivityTypeQuery is the builder for querying ActivityType entities.
type ActivityTypeQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.ActivityType
	// eager-loading edges.
	withActivities *ActivitiesQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (atq *ActivityTypeQuery) Where(ps ...predicate.ActivityType) *ActivityTypeQuery {
	atq.predicates = append(atq.predicates, ps...)
	return atq
}

// Limit adds a limit step to the query.
func (atq *ActivityTypeQuery) Limit(limit int) *ActivityTypeQuery {
	atq.limit = &limit
	return atq
}

// Offset adds an offset step to the query.
func (atq *ActivityTypeQuery) Offset(offset int) *ActivityTypeQuery {
	atq.offset = &offset
	return atq
}

// Order adds an order step to the query.
func (atq *ActivityTypeQuery) Order(o ...OrderFunc) *ActivityTypeQuery {
	atq.order = append(atq.order, o...)
	return atq
}

// QueryActivities chains the current query on the activities edge.
func (atq *ActivityTypeQuery) QueryActivities() *ActivitiesQuery {
	query := &ActivitiesQuery{config: atq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := atq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(activitytype.Table, activitytype.FieldID, atq.sqlQuery()),
			sqlgraph.To(activities.Table, activities.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, activitytype.ActivitiesTable, activitytype.ActivitiesColumn),
		)
		fromU = sqlgraph.SetNeighbors(atq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ActivityType entity in the query. Returns *NotFoundError when no activitytype was found.
func (atq *ActivityTypeQuery) First(ctx context.Context) (*ActivityType, error) {
	ats, err := atq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(ats) == 0 {
		return nil, &NotFoundError{activitytype.Label}
	}
	return ats[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (atq *ActivityTypeQuery) FirstX(ctx context.Context) *ActivityType {
	at, err := atq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return at
}

// FirstID returns the first ActivityType id in the query. Returns *NotFoundError when no id was found.
func (atq *ActivityTypeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = atq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{activitytype.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (atq *ActivityTypeQuery) FirstXID(ctx context.Context) int {
	id, err := atq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only ActivityType entity in the query, returns an error if not exactly one entity was returned.
func (atq *ActivityTypeQuery) Only(ctx context.Context) (*ActivityType, error) {
	ats, err := atq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(ats) {
	case 1:
		return ats[0], nil
	case 0:
		return nil, &NotFoundError{activitytype.Label}
	default:
		return nil, &NotSingularError{activitytype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (atq *ActivityTypeQuery) OnlyX(ctx context.Context) *ActivityType {
	at, err := atq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return at
}

// OnlyID returns the only ActivityType id in the query, returns an error if not exactly one id was returned.
func (atq *ActivityTypeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = atq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{activitytype.Label}
	default:
		err = &NotSingularError{activitytype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (atq *ActivityTypeQuery) OnlyIDX(ctx context.Context) int {
	id, err := atq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ActivityTypes.
func (atq *ActivityTypeQuery) All(ctx context.Context) ([]*ActivityType, error) {
	if err := atq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return atq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (atq *ActivityTypeQuery) AllX(ctx context.Context) []*ActivityType {
	ats, err := atq.All(ctx)
	if err != nil {
		panic(err)
	}
	return ats
}

// IDs executes the query and returns a list of ActivityType ids.
func (atq *ActivityTypeQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := atq.Select(activitytype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (atq *ActivityTypeQuery) IDsX(ctx context.Context) []int {
	ids, err := atq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (atq *ActivityTypeQuery) Count(ctx context.Context) (int, error) {
	if err := atq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return atq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (atq *ActivityTypeQuery) CountX(ctx context.Context) int {
	count, err := atq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (atq *ActivityTypeQuery) Exist(ctx context.Context) (bool, error) {
	if err := atq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return atq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (atq *ActivityTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := atq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (atq *ActivityTypeQuery) Clone() *ActivityTypeQuery {
	return &ActivityTypeQuery{
		config:     atq.config,
		limit:      atq.limit,
		offset:     atq.offset,
		order:      append([]OrderFunc{}, atq.order...),
		unique:     append([]string{}, atq.unique...),
		predicates: append([]predicate.ActivityType{}, atq.predicates...),
		// clone intermediate query.
		sql:  atq.sql.Clone(),
		path: atq.path,
	}
}

//  WithActivities tells the query-builder to eager-loads the nodes that are connected to
// the "activities" edge. The optional arguments used to configure the query builder of the edge.
func (atq *ActivityTypeQuery) WithActivities(opts ...func(*ActivitiesQuery)) *ActivityTypeQuery {
	query := &ActivitiesQuery{config: atq.config}
	for _, opt := range opts {
		opt(query)
	}
	atq.withActivities = query
	return atq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ActivityType.Query().
//		GroupBy(activitytype.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (atq *ActivityTypeQuery) GroupBy(field string, fields ...string) *ActivityTypeGroupBy {
	group := &ActivityTypeGroupBy{config: atq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := atq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return atq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ActivityType.Query().
//		Select(activitytype.FieldName).
//		Scan(ctx, &v)
//
func (atq *ActivityTypeQuery) Select(field string, fields ...string) *ActivityTypeSelect {
	selector := &ActivityTypeSelect{config: atq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := atq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return atq.sqlQuery(), nil
	}
	return selector
}

func (atq *ActivityTypeQuery) prepareQuery(ctx context.Context) error {
	if atq.path != nil {
		prev, err := atq.path(ctx)
		if err != nil {
			return err
		}
		atq.sql = prev
	}
	return nil
}

func (atq *ActivityTypeQuery) sqlAll(ctx context.Context) ([]*ActivityType, error) {
	var (
		nodes       = []*ActivityType{}
		_spec       = atq.querySpec()
		loadedTypes = [1]bool{
			atq.withActivities != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &ActivityType{config: atq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, atq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := atq.withActivities; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*ActivityType)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.Activities(func(s *sql.Selector) {
			s.Where(sql.InValues(activitytype.ActivitiesColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.ActivityTypeID
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "ActivityTypeID" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "ActivityTypeID" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Activities = append(node.Edges.Activities, n)
		}
	}

	return nodes, nil
}

func (atq *ActivityTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := atq.querySpec()
	return sqlgraph.CountNodes(ctx, atq.driver, _spec)
}

func (atq *ActivityTypeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := atq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (atq *ActivityTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   activitytype.Table,
			Columns: activitytype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: activitytype.FieldID,
			},
		},
		From:   atq.sql,
		Unique: true,
	}
	if ps := atq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := atq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := atq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := atq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (atq *ActivityTypeQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(atq.driver.Dialect())
	t1 := builder.Table(activitytype.Table)
	selector := builder.Select(t1.Columns(activitytype.Columns...)...).From(t1)
	if atq.sql != nil {
		selector = atq.sql
		selector.Select(selector.Columns(activitytype.Columns...)...)
	}
	for _, p := range atq.predicates {
		p(selector)
	}
	for _, p := range atq.order {
		p(selector)
	}
	if offset := atq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := atq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ActivityTypeGroupBy is the builder for group-by ActivityType entities.
type ActivityTypeGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (atgb *ActivityTypeGroupBy) Aggregate(fns ...AggregateFunc) *ActivityTypeGroupBy {
	atgb.fns = append(atgb.fns, fns...)
	return atgb
}

// Scan applies the group-by query and scan the result into the given value.
func (atgb *ActivityTypeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := atgb.path(ctx)
	if err != nil {
		return err
	}
	atgb.sql = query
	return atgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (atgb *ActivityTypeGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := atgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (atgb *ActivityTypeGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(atgb.fields) > 1 {
		return nil, errors.New("ent: ActivityTypeGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := atgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (atgb *ActivityTypeGroupBy) StringsX(ctx context.Context) []string {
	v, err := atgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (atgb *ActivityTypeGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = atgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{activitytype.Label}
	default:
		err = fmt.Errorf("ent: ActivityTypeGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (atgb *ActivityTypeGroupBy) StringX(ctx context.Context) string {
	v, err := atgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (atgb *ActivityTypeGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(atgb.fields) > 1 {
		return nil, errors.New("ent: ActivityTypeGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := atgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (atgb *ActivityTypeGroupBy) IntsX(ctx context.Context) []int {
	v, err := atgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (atgb *ActivityTypeGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = atgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{activitytype.Label}
	default:
		err = fmt.Errorf("ent: ActivityTypeGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (atgb *ActivityTypeGroupBy) IntX(ctx context.Context) int {
	v, err := atgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (atgb *ActivityTypeGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(atgb.fields) > 1 {
		return nil, errors.New("ent: ActivityTypeGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := atgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (atgb *ActivityTypeGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := atgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (atgb *ActivityTypeGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = atgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{activitytype.Label}
	default:
		err = fmt.Errorf("ent: ActivityTypeGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (atgb *ActivityTypeGroupBy) Float64X(ctx context.Context) float64 {
	v, err := atgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (atgb *ActivityTypeGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(atgb.fields) > 1 {
		return nil, errors.New("ent: ActivityTypeGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := atgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (atgb *ActivityTypeGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := atgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (atgb *ActivityTypeGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = atgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{activitytype.Label}
	default:
		err = fmt.Errorf("ent: ActivityTypeGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (atgb *ActivityTypeGroupBy) BoolX(ctx context.Context) bool {
	v, err := atgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (atgb *ActivityTypeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := atgb.sqlQuery().Query()
	if err := atgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (atgb *ActivityTypeGroupBy) sqlQuery() *sql.Selector {
	selector := atgb.sql
	columns := make([]string, 0, len(atgb.fields)+len(atgb.fns))
	columns = append(columns, atgb.fields...)
	for _, fn := range atgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(atgb.fields...)
}

// ActivityTypeSelect is the builder for select fields of ActivityType entities.
type ActivityTypeSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (ats *ActivityTypeSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := ats.path(ctx)
	if err != nil {
		return err
	}
	ats.sql = query
	return ats.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ats *ActivityTypeSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ats.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (ats *ActivityTypeSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ats.fields) > 1 {
		return nil, errors.New("ent: ActivityTypeSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ats.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ats *ActivityTypeSelect) StringsX(ctx context.Context) []string {
	v, err := ats.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (ats *ActivityTypeSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ats.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{activitytype.Label}
	default:
		err = fmt.Errorf("ent: ActivityTypeSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ats *ActivityTypeSelect) StringX(ctx context.Context) string {
	v, err := ats.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (ats *ActivityTypeSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ats.fields) > 1 {
		return nil, errors.New("ent: ActivityTypeSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ats.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ats *ActivityTypeSelect) IntsX(ctx context.Context) []int {
	v, err := ats.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (ats *ActivityTypeSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ats.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{activitytype.Label}
	default:
		err = fmt.Errorf("ent: ActivityTypeSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ats *ActivityTypeSelect) IntX(ctx context.Context) int {
	v, err := ats.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (ats *ActivityTypeSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ats.fields) > 1 {
		return nil, errors.New("ent: ActivityTypeSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ats.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ats *ActivityTypeSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ats.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (ats *ActivityTypeSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ats.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{activitytype.Label}
	default:
		err = fmt.Errorf("ent: ActivityTypeSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ats *ActivityTypeSelect) Float64X(ctx context.Context) float64 {
	v, err := ats.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (ats *ActivityTypeSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ats.fields) > 1 {
		return nil, errors.New("ent: ActivityTypeSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ats.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ats *ActivityTypeSelect) BoolsX(ctx context.Context) []bool {
	v, err := ats.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (ats *ActivityTypeSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ats.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{activitytype.Label}
	default:
		err = fmt.Errorf("ent: ActivityTypeSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ats *ActivityTypeSelect) BoolX(ctx context.Context) bool {
	v, err := ats.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ats *ActivityTypeSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ats.sqlQuery().Query()
	if err := ats.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ats *ActivityTypeSelect) sqlQuery() sql.Querier {
	selector := ats.sql
	selector.Select(selector.Columns(ats.fields...)...)
	return selector
}
