// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/OMENX/app/ent/activitytype"
	"github.com/facebookincubator/ent/dialect/sql"
)

// ActivityType is the model entity for the ActivityType schema.
type ActivityType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ActivityTypeQuery when eager-loading is set.
	Edges ActivityTypeEdges `json:"edges"`
}

// ActivityTypeEdges holds the relations/edges for other nodes in the graph.
type ActivityTypeEdges struct {
	// Activities holds the value of the activities edge.
	Activities []*Activities
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ActivitiesOrErr returns the Activities value or an error if the edge
// was not loaded in eager-loading.
func (e ActivityTypeEdges) ActivitiesOrErr() ([]*Activities, error) {
	if e.loadedTypes[0] {
		return e.Activities, nil
	}
	return nil, &NotLoadedError{edge: "activities"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ActivityType) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ActivityType fields.
func (at *ActivityType) assignValues(values ...interface{}) error {
	if m, n := len(values), len(activitytype.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	at.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		at.Name = value.String
	}
	return nil
}

// QueryActivities queries the activities edge of the ActivityType.
func (at *ActivityType) QueryActivities() *ActivitiesQuery {
	return (&ActivityTypeClient{config: at.config}).QueryActivities(at)
}

// Update returns a builder for updating this ActivityType.
// Note that, you need to call ActivityType.Unwrap() before calling this method, if this ActivityType
// was returned from a transaction, and the transaction was committed or rolled back.
func (at *ActivityType) Update() *ActivityTypeUpdateOne {
	return (&ActivityTypeClient{config: at.config}).UpdateOne(at)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (at *ActivityType) Unwrap() *ActivityType {
	tx, ok := at.config.driver.(*txDriver)
	if !ok {
		panic("ent: ActivityType is not a transactional entity")
	}
	at.config.driver = tx.drv
	return at
}

// String implements the fmt.Stringer.
func (at *ActivityType) String() string {
	var builder strings.Builder
	builder.WriteString("ActivityType(")
	builder.WriteString(fmt.Sprintf("id=%v", at.ID))
	builder.WriteString(", name=")
	builder.WriteString(at.Name)
	builder.WriteByte(')')
	return builder.String()
}

// ActivityTypes is a parsable slice of ActivityType.
type ActivityTypes []*ActivityType

func (at ActivityTypes) config(cfg config) {
	for _i := range at {
		at[_i].config = cfg
	}
}
