// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/OMENX/app/ent/clubbranch"
	"github.com/OMENX/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ClubBranchDelete is the builder for deleting a ClubBranch entity.
type ClubBranchDelete struct {
	config
	hooks      []Hook
	mutation   *ClubBranchMutation
	predicates []predicate.ClubBranch
}

// Where adds a new predicate to the delete builder.
func (cbd *ClubBranchDelete) Where(ps ...predicate.ClubBranch) *ClubBranchDelete {
	cbd.predicates = append(cbd.predicates, ps...)
	return cbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cbd *ClubBranchDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cbd.hooks) == 0 {
		affected, err = cbd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ClubBranchMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cbd.mutation = mutation
			affected, err = cbd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cbd.hooks) - 1; i >= 0; i-- {
			mut = cbd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cbd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cbd *ClubBranchDelete) ExecX(ctx context.Context) int {
	n, err := cbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cbd *ClubBranchDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: clubbranch.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: clubbranch.FieldID,
			},
		},
	}
	if ps := cbd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, cbd.driver, _spec)
}

// ClubBranchDeleteOne is the builder for deleting a single ClubBranch entity.
type ClubBranchDeleteOne struct {
	cbd *ClubBranchDelete
}

// Exec executes the deletion query.
func (cbdo *ClubBranchDeleteOne) Exec(ctx context.Context) error {
	n, err := cbdo.cbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{clubbranch.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cbdo *ClubBranchDeleteOne) ExecX(ctx context.Context) {
	cbdo.cbd.ExecX(ctx)
}
