// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/OMENX/app/ent/clubtype"
	"github.com/facebookincubator/ent/dialect/sql"
)

// ClubType is the model entity for the ClubType schema.
type ClubType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClubTypeQuery when eager-loading is set.
	Edges ClubTypeEdges `json:"edges"`
}

// ClubTypeEdges holds the relations/edges for other nodes in the graph.
type ClubTypeEdges struct {
	// Club holds the value of the club edge.
	Club []*Club
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ClubOrErr returns the Club value or an error if the edge
// was not loaded in eager-loading.
func (e ClubTypeEdges) ClubOrErr() ([]*Club, error) {
	if e.loadedTypes[0] {
		return e.Club, nil
	}
	return nil, &NotLoadedError{edge: "club"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ClubType) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ClubType fields.
func (ct *ClubType) assignValues(values ...interface{}) error {
	if m, n := len(values), len(clubtype.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ct.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		ct.Name = value.String
	}
	return nil
}

// QueryClub queries the club edge of the ClubType.
func (ct *ClubType) QueryClub() *ClubQuery {
	return (&ClubTypeClient{config: ct.config}).QueryClub(ct)
}

// Update returns a builder for updating this ClubType.
// Note that, you need to call ClubType.Unwrap() before calling this method, if this ClubType
// was returned from a transaction, and the transaction was committed or rolled back.
func (ct *ClubType) Update() *ClubTypeUpdateOne {
	return (&ClubTypeClient{config: ct.config}).UpdateOne(ct)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ct *ClubType) Unwrap() *ClubType {
	tx, ok := ct.config.driver.(*txDriver)
	if !ok {
		panic("ent: ClubType is not a transactional entity")
	}
	ct.config.driver = tx.drv
	return ct
}

// String implements the fmt.Stringer.
func (ct *ClubType) String() string {
	var builder strings.Builder
	builder.WriteString("ClubType(")
	builder.WriteString(fmt.Sprintf("id=%v", ct.ID))
	builder.WriteString(", name=")
	builder.WriteString(ct.Name)
	builder.WriteByte(')')
	return builder.String()
}

// ClubTypes is a parsable slice of ClubType.
type ClubTypes []*ClubType

func (ct ClubTypes) config(cfg config) {
	for _i := range ct {
		ct[_i].config = cfg
	}
}
