// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/OMENX/app/ent/predicate"
	"github.com/OMENX/app/ent/roompurpose"
	"github.com/OMENX/app/ent/roomuse"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RoompurposeUpdate is the builder for updating Roompurpose entities.
type RoompurposeUpdate struct {
	config
	hooks      []Hook
	mutation   *RoompurposeMutation
	predicates []predicate.Roompurpose
}

// Where adds a new predicate for the builder.
func (ru *RoompurposeUpdate) Where(ps ...predicate.Roompurpose) *RoompurposeUpdate {
	ru.predicates = append(ru.predicates, ps...)
	return ru
}

// SetPurpose sets the purpose field.
func (ru *RoompurposeUpdate) SetPurpose(s string) *RoompurposeUpdate {
	ru.mutation.SetPurpose(s)
	return ru
}

// AddRoompurposeIDs adds the roompurpose edge to Roomuse by ids.
func (ru *RoompurposeUpdate) AddRoompurposeIDs(ids ...int) *RoompurposeUpdate {
	ru.mutation.AddRoompurposeIDs(ids...)
	return ru
}

// AddRoompurpose adds the roompurpose edges to Roomuse.
func (ru *RoompurposeUpdate) AddRoompurpose(r ...*Roomuse) *RoompurposeUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.AddRoompurposeIDs(ids...)
}

// Mutation returns the RoompurposeMutation object of the builder.
func (ru *RoompurposeUpdate) Mutation() *RoompurposeMutation {
	return ru.mutation
}

// RemoveRoompurposeIDs removes the roompurpose edge to Roomuse by ids.
func (ru *RoompurposeUpdate) RemoveRoompurposeIDs(ids ...int) *RoompurposeUpdate {
	ru.mutation.RemoveRoompurposeIDs(ids...)
	return ru
}

// RemoveRoompurpose removes roompurpose edges to Roomuse.
func (ru *RoompurposeUpdate) RemoveRoompurpose(r ...*Roomuse) *RoompurposeUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.RemoveRoompurposeIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (ru *RoompurposeUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := ru.mutation.Purpose(); ok {
		if err := roompurpose.PurposeValidator(v); err != nil {
			return 0, &ValidationError{Name: "purpose", err: fmt.Errorf("ent: validator failed for field \"purpose\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(ru.hooks) == 0 {
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoompurposeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RoompurposeUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RoompurposeUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RoompurposeUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RoompurposeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roompurpose.Table,
			Columns: roompurpose.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roompurpose.FieldID,
			},
		},
	}
	if ps := ru.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Purpose(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roompurpose.FieldPurpose,
		})
	}
	if nodes := ru.mutation.RemovedRoompurposeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roompurpose.RoompurposeTable,
			Columns: []string{roompurpose.RoompurposeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomuse.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RoompurposeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roompurpose.RoompurposeTable,
			Columns: []string{roompurpose.RoompurposeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomuse.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roompurpose.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// RoompurposeUpdateOne is the builder for updating a single Roompurpose entity.
type RoompurposeUpdateOne struct {
	config
	hooks    []Hook
	mutation *RoompurposeMutation
}

// SetPurpose sets the purpose field.
func (ruo *RoompurposeUpdateOne) SetPurpose(s string) *RoompurposeUpdateOne {
	ruo.mutation.SetPurpose(s)
	return ruo
}

// AddRoompurposeIDs adds the roompurpose edge to Roomuse by ids.
func (ruo *RoompurposeUpdateOne) AddRoompurposeIDs(ids ...int) *RoompurposeUpdateOne {
	ruo.mutation.AddRoompurposeIDs(ids...)
	return ruo
}

// AddRoompurpose adds the roompurpose edges to Roomuse.
func (ruo *RoompurposeUpdateOne) AddRoompurpose(r ...*Roomuse) *RoompurposeUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.AddRoompurposeIDs(ids...)
}

// Mutation returns the RoompurposeMutation object of the builder.
func (ruo *RoompurposeUpdateOne) Mutation() *RoompurposeMutation {
	return ruo.mutation
}

// RemoveRoompurposeIDs removes the roompurpose edge to Roomuse by ids.
func (ruo *RoompurposeUpdateOne) RemoveRoompurposeIDs(ids ...int) *RoompurposeUpdateOne {
	ruo.mutation.RemoveRoompurposeIDs(ids...)
	return ruo
}

// RemoveRoompurpose removes roompurpose edges to Roomuse.
func (ruo *RoompurposeUpdateOne) RemoveRoompurpose(r ...*Roomuse) *RoompurposeUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.RemoveRoompurposeIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (ruo *RoompurposeUpdateOne) Save(ctx context.Context) (*Roompurpose, error) {
	if v, ok := ruo.mutation.Purpose(); ok {
		if err := roompurpose.PurposeValidator(v); err != nil {
			return nil, &ValidationError{Name: "purpose", err: fmt.Errorf("ent: validator failed for field \"purpose\": %w", err)}
		}
	}

	var (
		err  error
		node *Roompurpose
	)
	if len(ruo.hooks) == 0 {
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoompurposeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			mut = ruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RoompurposeUpdateOne) SaveX(ctx context.Context) *Roompurpose {
	r, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return r
}

// Exec executes the query on the entity.
func (ruo *RoompurposeUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RoompurposeUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RoompurposeUpdateOne) sqlSave(ctx context.Context) (r *Roompurpose, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roompurpose.Table,
			Columns: roompurpose.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roompurpose.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Roompurpose.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := ruo.mutation.Purpose(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roompurpose.FieldPurpose,
		})
	}
	if nodes := ruo.mutation.RemovedRoompurposeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roompurpose.RoompurposeTable,
			Columns: []string{roompurpose.RoompurposeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomuse.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RoompurposeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roompurpose.RoompurposeTable,
			Columns: []string{roompurpose.RoompurposeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomuse.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	r = &Roompurpose{config: ruo.config}
	_spec.Assign = r.assignValues
	_spec.ScanValues = r.scanValues()
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roompurpose.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return r, nil
}
