// Code generated by entc, DO NOT EDIT.

package clubappstatus

const (
	// Label holds the string label denoting the clubappstatus type in the database.
	Label = "clubapp_status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClubstatus holds the string denoting the clubstatus field in the database.
	FieldClubstatus = "clubstatus"

	// EdgeClubapplication holds the string denoting the clubapplication edge name in mutations.
	EdgeClubapplication = "clubapplication"

	// Table holds the table name of the clubappstatus in the database.
	Table = "clubapp_status"
	// ClubapplicationTable is the table the holds the clubapplication relation/edge.
	ClubapplicationTable = "clubapplications"
	// ClubapplicationInverseTable is the table name for the Clubapplication entity.
	// It exists in this package in order to avoid circular dependency with the "clubapplication" package.
	ClubapplicationInverseTable = "clubapplications"
	// ClubapplicationColumn is the table column denoting the clubapplication relation/edge.
	ClubapplicationColumn = "clubstatusID"
)

// Columns holds all SQL columns for clubappstatus fields.
var Columns = []string{
	FieldID,
	FieldClubstatus,
}
