// Code generated by entc, DO NOT EDIT.

package clubbranch

const (
	// Label holds the string label denoting the clubbranch type in the database.
	Label = "club_branch"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeClub holds the string denoting the club edge name in mutations.
	EdgeClub = "club"

	// Table holds the table name of the clubbranch in the database.
	Table = "club_branches"
	// ClubTable is the table the holds the club relation/edge.
	ClubTable = "clubs"
	// ClubInverseTable is the table name for the Club entity.
	// It exists in this package in order to avoid circular dependency with the "club" package.
	ClubInverseTable = "clubs"
	// ClubColumn is the table column denoting the club relation/edge.
	ClubColumn = "ClubBranch_ID"
)

// Columns holds all SQL columns for clubbranch fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
