/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersComplaint
 */
export interface ControllersComplaint {
    /**
     * 
     * @type {number}
     * @memberof ControllersComplaint
     */
    clubID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersComplaint
     */
    typeID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersComplaint
     */
    userID?: number;
}

export function ControllersComplaintFromJSON(json: any): ControllersComplaint {
    return ControllersComplaintFromJSONTyped(json, false);
}

export function ControllersComplaintFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersComplaint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clubID': !exists(json, 'clubID') ? undefined : json['clubID'],
        'typeID': !exists(json, 'typeID') ? undefined : json['typeID'],
        'userID': !exists(json, 'userID') ? undefined : json['userID'],
    };
}

export function ControllersComplaintToJSON(value?: ControllersComplaint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clubID': value.clubID,
        'typeID': value.typeID,
        'userID': value.userID,
    };
}


