/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersClubapplication
 */
export interface ControllersClubapplication {
    /**
     * 
     * @type {string}
     * @memberof ControllersClubapplication
     */
    addedtime?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersClubapplication
     */
    adderAge?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersClubapplication
     */
    adderGender?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersClubapplication
     */
    adderName?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersClubapplication
     */
    appstatusID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersClubapplication
     */
    clubID?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersClubapplication
     */
    contact?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersClubapplication
     */
    discipline?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersClubapplication
     */
    reason?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersClubapplication
     */
    userID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersClubapplication
     */
    year?: number;
}

export function ControllersClubapplicationFromJSON(json: any): ControllersClubapplication {
    return ControllersClubapplicationFromJSONTyped(json, false);
}

export function ControllersClubapplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersClubapplication {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addedtime': !exists(json, 'addedtime') ? undefined : json['addedtime'],
        'adderAge': !exists(json, 'adderAge') ? undefined : json['adderAge'],
        'adderGender': !exists(json, 'adderGender') ? undefined : json['adderGender'],
        'adderName': !exists(json, 'adderName') ? undefined : json['adderName'],
        'appstatusID': !exists(json, 'appstatusID') ? undefined : json['appstatusID'],
        'clubID': !exists(json, 'clubID') ? undefined : json['clubID'],
        'contact': !exists(json, 'contact') ? undefined : json['contact'],
        'discipline': !exists(json, 'discipline') ? undefined : json['discipline'],
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
        'userID': !exists(json, 'userID') ? undefined : json['userID'],
        'year': !exists(json, 'year') ? undefined : json['year'],
    };
}

export function ControllersClubapplicationToJSON(value?: ControllersClubapplication | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addedtime': value.addedtime,
        'adderAge': value.adderAge,
        'adderGender': value.adderGender,
        'adderName': value.adderName,
        'appstatusID': value.appstatusID,
        'clubID': value.clubID,
        'contact': value.contact,
        'discipline': value.discipline,
        'reason': value.reason,
        'userID': value.userID,
        'year': value.year,
    };
}


