/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntAcademicYear,
    EntAcademicYearFromJSON,
    EntAcademicYearFromJSONTyped,
    EntAcademicYearToJSON,
    EntActivityType,
    EntActivityTypeFromJSON,
    EntActivityTypeFromJSONTyped,
    EntActivityTypeToJSON,
    EntClub,
    EntClubFromJSON,
    EntClubFromJSONTyped,
    EntClubToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntActivitiesEdges
 */
export interface EntActivitiesEdges {
    /**
     * 
     * @type {EntAcademicYear}
     * @memberof EntActivitiesEdges
     */
    academicyear?: EntAcademicYear;
    /**
     * 
     * @type {EntActivityType}
     * @memberof EntActivitiesEdges
     */
    activitytype?: EntActivityType;
    /**
     * 
     * @type {EntClub}
     * @memberof EntActivitiesEdges
     */
    club?: EntClub;
}

export function EntActivitiesEdgesFromJSON(json: any): EntActivitiesEdges {
    return EntActivitiesEdgesFromJSONTyped(json, false);
}

export function EntActivitiesEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntActivitiesEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'academicyear': !exists(json, 'academicyear') ? undefined : EntAcademicYearFromJSON(json['academicyear']),
        'activitytype': !exists(json, 'activitytype') ? undefined : EntActivityTypeFromJSON(json['activitytype']),
        'club': !exists(json, 'club') ? undefined : EntClubFromJSON(json['club']),
    };
}

export function EntActivitiesEdgesToJSON(value?: EntActivitiesEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'academicyear': EntAcademicYearToJSON(value.academicyear),
        'activitytype': EntActivityTypeToJSON(value.activitytype),
        'club': EntClubToJSON(value.club),
    };
}


