/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntActivities,
    EntActivitiesFromJSON,
    EntActivitiesFromJSONTyped,
    EntActivitiesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntAcademicYearEdges
 */
export interface EntAcademicYearEdges {
    /**
     * Activities holds the value of the activities edge.
     * @type {Array<EntActivities>}
     * @memberof EntAcademicYearEdges
     */
    activities?: Array<EntActivities>;
}

export function EntAcademicYearEdgesFromJSON(json: any): EntAcademicYearEdges {
    return EntAcademicYearEdgesFromJSONTyped(json, false);
}

export function EntAcademicYearEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntAcademicYearEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'activities': !exists(json, 'activities') ? undefined : ((json['activities'] as Array<any>).map(EntActivitiesFromJSON)),
    };
}

export function EntAcademicYearEdgesToJSON(value?: EntAcademicYearEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'activities': value.activities === undefined ? undefined : ((value.activities as Array<any>).map(EntActivitiesToJSON)),
    };
}


