/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntClubBranchEdges,
    EntClubBranchEdgesFromJSON,
    EntClubBranchEdgesFromJSONTyped,
    EntClubBranchEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntClubBranch
 */
export interface EntClubBranch {
    /**
     * 
     * @type {EntClubBranchEdges}
     * @memberof EntClubBranch
     */
    edges?: EntClubBranchEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntClubBranch
     */
    id?: number;
    /**
     * Name holds the value of the "name" field.
     * @type {string}
     * @memberof EntClubBranch
     */
    name?: string;
}

export function EntClubBranchFromJSON(json: any): EntClubBranch {
    return EntClubBranchFromJSONTyped(json, false);
}

export function EntClubBranchFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntClubBranch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntClubBranchEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function EntClubBranchToJSON(value?: EntClubBranch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntClubBranchEdgesToJSON(value.edges),
        'id': value.id,
        'name': value.name,
    };
}


