/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPurposeEdges,
    EntPurposeEdgesFromJSON,
    EntPurposeEdgesFromJSONTyped,
    EntPurposeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPurpose
 */
export interface EntPurpose {
    /**
     * 
     * @type {EntPurposeEdges}
     * @memberof EntPurpose
     */
    edges?: EntPurposeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPurpose
     */
    id?: number;
    /**
     * Purpose holds the value of the "purpose" field.
     * @type {string}
     * @memberof EntPurpose
     */
    purpose?: string;
}

export function EntPurposeFromJSON(json: any): EntPurpose {
    return EntPurposeFromJSONTyped(json, false);
}

export function EntPurposeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPurpose {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntPurposeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'purpose': !exists(json, 'purpose') ? undefined : json['purpose'],
    };
}

export function EntPurposeToJSON(value?: EntPurpose | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntPurposeEdgesToJSON(value.edges),
        'id': value.id,
        'purpose': value.purpose,
    };
}


