/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRoomuse,
    EntRoomuseFromJSON,
    EntRoomuseFromJSONTyped,
    EntRoomuseToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPurposeEdges
 */
export interface EntPurposeEdges {
    /**
     * Roomuses holds the value of the roomuses edge.
     * @type {Array<EntRoomuse>}
     * @memberof EntPurposeEdges
     */
    roomuses?: Array<EntRoomuse>;
}

export function EntPurposeEdgesFromJSON(json: any): EntPurposeEdges {
    return EntPurposeEdgesFromJSONTyped(json, false);
}

export function EntPurposeEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPurposeEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roomuses': !exists(json, 'roomuses') ? undefined : ((json['roomuses'] as Array<any>).map(EntRoomuseFromJSON)),
    };
}

export function EntPurposeEdgesToJSON(value?: EntPurposeEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roomuses': value.roomuses === undefined ? undefined : ((value.roomuses as Array<any>).map(EntRoomuseToJSON)),
    };
}


